site_name: Barco Streams
repo_url: https://github.com/barcostreams/barco
edit_uri: blob/main/docs/
docs_dir: docs

nav:
  - Overview: 'README.md'
  - About: 'TECHNICAL_INTRO.md'
  - Install: 'install/README.md'
  - Getting Started:
    - Getting Started on Docker: 'getting_started/ON_DOCKER.md'
    - Getting Started on Kubernetes: 'getting_started/ON_KUBERNETES.md'
  - REST API docs: 'REST_API.md'
  - Benchmarks: 'BENCHMARKS.md'
  - FAQ: FAQ.md

copyright: >-


theme:
  name: material
  palette:
    primary: indigo
    accent: red
  font:
    text: Lato
    code: Ubuntu Mono
  logo: images/barco-dark.jpg
  favicon: images/barco-dark.jpg
  features:
    - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition

plugins:
  - search
  - build_plantuml:
      render: "server"
      server: "http://www.plantuml.com/plantuml"
      output_format: "png"
      diagram_root: "docs"
      output_folder: "target"
      input_folder: "diagrams"
      input_extensions: "puml"
  - macros
