replicaCount: 3

image:
  registry: docker.io
  repository: polarstreams/polar
  pullPolicy: IfNotPresent
  version: "latest"

imagePullSecrets: []
nameOverride: ""
namespaceOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  enabled: true

securityContext:
  enabled: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  runAsNonRoot: true

service:
  type: ClusterIP
  annotations: {}
  ports:
    - name: discovery
      protocol: TCP
      port: 9250
      targetPort: discovery
    - name: producer
      protocol: TCP
      port: 9251
      targetPort: producer
    - name: consumer
      protocol: TCP
      port: 9252
      targetPort: consumer

prometheus:
  enabled: true
  port: "9253"

extraEnvVars: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

resourceFieldRef:
  limitsMemory:
    divisor: 1Ki
  requestsCpu:
    divisor: 1m

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true
