{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "polar.fullname" . }}
  namespace: {{ include "polar.namespace" . | quote }}
  labels:
    {{- include "polar.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get","list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list", "watch"]
{{- end }}
