apiVersion: v1
kind: Service
metadata:
  name: {{ include "polar.fullname" . }}
  labels:
    {{- include "polar.labels" . | nindent 4 }}
  {{- if or .Values.prometheus.enabled .Values.service.annotations }}
  annotations:
  {{- if .Values.prometheus.annotations }}
    {{- toYaml (.Values.service.annotations) . | nindent 4 }}
  {{- end }}
  {{- if .Values.prometheus.enabled }}
    prometheus.io/port: "{{ .Values.prometheus.port }}"
    prometheus.io/scrape: "true"
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- tpl (toYaml .Values.service.ports) . | nindent 4 }}
  selector:
    {{- include "polar.selectorLabels" . | nindent 4 }}
