---
apiVersion: v1
kind: Service
metadata:
  name: polar
  namespace: polar
spec:
  selector:
    name: polar
  ports:
  - name: discovery
    protocol: TCP
    port: 9250
    targetPort: discovery
  - name: producer
    protocol: TCP
    port: 9251
    targetPort: producer
  - name: consumer
    protocol: TCP
    port: 9252
    targetPort: consumer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: polar
  namespace: polar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: polar
  namespace: polar
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get","list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: polar
  namespace: polar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: polar
subjects:
  - kind: ServiceAccount
    name: polar
    namespace: polar
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: polar
  namespace: polar
  labels:
      app.kubernetes.io/name: polar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: polar
      name: polar
  serviceName: polar
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: polar
        name: polar
      annotations:
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: polar
      terminationGracePeriodSeconds: 60
      containers:
      - name: polar
        image: polarstreams/polar:latest
        imagePullPolicy: Always
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 9250
          name: discovery
        - containerPort: 9251
          name: producer
        - containerPort: 9252
          name: consumer
        env:
        - name: POLAR_SERVICE_NAME
          value: polar
        - name: POLAR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POLAR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_CPU_REQUEST_MILLICORES
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
              divisor: 1m
        - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: 1Ki
