name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build ./...

    - name: Unit tests
      run: go test -v ./...

    - name: Integration tests
      run: go test -v -tags=integration -p=1 ./internal/test/integration

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --tests=false --timeout=3m
          
  run_on_arm64:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
       - uses: actions/checkout@v3
         
       - name: Run on aarch64
         uses: uraimo/run-on-arch-action@v2
         with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          base_image: golang:1.19
          install: |
                apt-get update -q -y
                apt-get install -q -y git
          run: |
            git config --global --add safe.directory "$PWD"
            go build ./...
            go test -v ./... 
            go test -v -tags=integration -p=1 ./internal/test/integration
   
            
    
    
